locale: "pt-br"
backend:
  name: github
  repo: guilhermebellotti/template-gatsby-bellotti

publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "contents/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Data de publicação",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "string" }
      - {
          label: "Status",
          name: "active",
          widget: "select",
          default: "yes",
          options:
            [
              { label: "Ativado", value: "yes" },
              { label: "Desativado", value: "no" },
            ],
        }
      - {
          label: "Imagem de destaque",
          name: "image",
          widget: "image",
          default: "img/uploads/default-image.jpg",
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "contato" # Used in routes, e.g., /admin/collections/blog
    label: "Contato" # Used in the UI
    folder: "contents/contato" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Data de publicação",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD hh:mm:ss",
        }
      - { label: "Título (da página)", name: "title", widget: "string" }
      - {
          label: "Status",
          name: "active",
          widget: "select",
          default: "yes",
          options:
            [
              { label: "Ativado", value: "yes" },
              { label: "Desativado", value: "no" },
            ],
        }
      - {
          label: "Imagem de destaque",
          name: "image",
          widget: "image",
          default: "img/uploads/default-image.jpg",
        }
      - { label: "Body", name: "body", widget: "markdown" }
